# golangci-lint configuration (v2)
# See CONTRIBUTING.md for rationale on each linter.

version: "2"

run:
  modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true

linters:
  default: none
  enable:
    # Core linters (non-negotiable per CONTRIBUTING.md)
    - errcheck      # Unchecked errors - critical for distributed systems
    - staticcheck   # Gold standard Go static analysis
    - govet         # Catches subtle issues
    - gosec         # Security vulnerabilities (ADR-013)
    - bodyclose     # HTTP response body leaks
    - noctx         # HTTP requests missing context (ADR-009)

    # Strongly recommended
    - errname       # Error type naming conventions
    - errorlint     # Proper errors.Is/As usage
    - exhaustive    # Exhaustive switch on enums
    - revive        # Configurable style enforcement
    - gocritic      # Opinionated but catches real bugs
    - misspell      # Typos
    - unconvert     # Unnecessary type conversions
    - unparam       # Unused function parameters

    # Complexity
    - gocyclo       # Cyclomatic complexity
    - gocognit      # Cognitive complexity

  settings:
    gocyclo:
      min-complexity: 16  # Per CONTRIBUTING.md; error mappers legitimately have 16 cases

    gocognit:
      min-complexity: 20  # Per CONTRIBUTING.md

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Not critical for this project; causes noise

    revive:
      rules:
        - name: exported
          arguments:
            - checkPrivateReceivers
            - sayRepetitiveInsteadOfStutters
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: var-naming
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf

    gosec:
      excludes:
        - G104  # Unhandled errors (covered by errcheck)

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      # Relax rules for test files
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
      # Exclude generated code
      - linters:
          - errcheck
          - gosec
          - govet
        path: gen/
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
