# Auth secret containers — JWT signing material and the OTP pepper (ADR-015
# §1.2, §3.2, re-homed to GCP in its Appendix F).
#
# This module creates secrets and never creates versions. Key material is
# generated by scripts/auth-keys.sh and added with `gcloud secrets versions
# add`, so no private key or pepper ever enters Terraform state or a plan file.
# It is the same split M0.3 used for the schema registry, for the same reason:
# state should not claim what it should not hold.
#
# The consequence to expect is that a fresh `terraform apply` leaves four empty
# secrets, and ChatMgmt refuses to start against them — deliberately, per
# ADR-015's signing_key_required_for_startup. scripts/deploy.sh runs the key
# script between apply and rollout so this window never reaches a deploy.

locals {
  # One secret per piece of material. Secret Manager IDs are flat names rather
  # than paths, so structure is encoded with hyphens (ADR-015 Appendix F).
  secret_ids = {
    signing_key    = "jwt-signing-key-${var.signing_key_id}"
    public_key     = "jwt-public-key-${var.signing_key_id}"
    current_key_id = "jwt-current-key-id"
    otp_pepper     = "otp-pepper"
  }
}

resource "google_secret_manager_secret" "auth" {
  for_each = local.secret_ids

  project   = var.project_id
  secret_id = each.value

  # Automatic replication: this is a single-region lab, and pinning replicas
  # would buy nothing the region itself does not already decide.
  replication {
    auto {}
  }

  labels = var.labels
}

# Accessor bindings are granted per secret, not per service: the caller names
# which secrets each member may read, so a service that only verifies tokens can
# be granted the public key without also being handed the key that signs them
# (ADR-015 §3.2's least-privilege table).
#
# The keyed input is the whole point. An earlier revision took a flat member
# list and crossed it with every secret, which made the least-privilege claim
# above unenforceable — the first token-validating service added to the list
# would silently gain token-minting capability.
resource "google_secret_manager_secret_iam_member" "accessors" {
  for_each = {
    for binding in flatten([
      for secret, members in var.accessor_members : [
        for member in members : { secret = secret, member = member }
      ]
    ]) : "${binding.secret}:${binding.member}" => binding
  }

  project   = var.project_id
  secret_id = google_secret_manager_secret.auth[each.value.secret].secret_id
  role      = "roles/secretmanager.secretAccessor"
  member    = each.value.member
}
